import Foundation

/// Input that would build firmware that cannot work.
public struct ConfigError: LocalizedError, Equatable {
    public let message: String
    public init(_ message: String) { self.message = message }
    public var errorDescription: String? { message }
}

/// Reads and writes everything the flasher generates.
///
/// Three files come out of here, all gitignored:
///
///   `include/secrets.h`        credentials, the same file you would hand-copy
///                              from `secrets.example.h`
///   `include/device_config.h`  hub MACs, rooms, channel -- overrides the
///                              defaults in `include/config.h`
///   `platformio_local.ini`     one build environment per configured remote
///
/// `state.json` holds everything except the credentials. Those are read back out
/// of `secrets.h` instead of being duplicated, so there is exactly one copy of
/// your passwords on disk rather than two.
///
/// Interchangeable with `tools/flasher`: both tools read each other's files and
/// generate identical content, down to the byte, apart from the banner naming
/// whichever one wrote it. A project can be driven from the app or the browser
/// tool on alternate days without either standing on the other's work.
public struct ConfigStore: Sendable {
    public let root: URL

    public init(root: URL) { self.root = root }

    public var secretsURL: URL { root.appendingPathComponent("include/secrets.h") }
    public var deviceConfigURL: URL { root.appendingPathComponent("include/device_config.h") }
    public var localIniURL: URL { root.appendingPathComponent("platformio_local.ini") }
    public var stateURL: URL { root.appendingPathComponent("tools/flasher/state.json") }

    /// Names the tool so whoever opens the file knows where to change it. The
    /// Python flasher writes the same line with its own name in place of this
    /// one; nothing reads it back.
    static let generatedBanner =
        "// Generated by the ESP-NOW Remote Flasher app. Edits here are overwritten."

    /// Mirrors `MAX_LOCATION_LEN` in `include/config.h`. A longer name is
    /// silently truncated on the wire and the hub then rejects the packet, so it
    /// is caught here where the message can say why.
    public static let maxLocationLength = 15

    /// A hub already uses each of these as its `HUB_ID`; a location colliding
    /// with one would collide on the node id too.
    static let reservedLocations: Set<String> = ["wifi", "eth"]

    // MARK: - state.json

    public func loadState() throws -> FlasherState {
        guard let data = try? Data(contentsOf: stateURL) else { return FlasherState() }
        // Corrupt state should not lock you out of the UI; the defaults are
        // always a usable starting point.
        return (try? JSONDecoder().decode(FlasherState.self, from: data)) ?? FlasherState()
    }

    public func saveState(_ state: FlasherState) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        var data = try encoder.encode(state)
        data.append(0x0A)
        try createParentDirectory(of: stateURL)
        try write(data, to: stateURL)
    }

    // MARK: - secrets.h

    /// Reads the credentials back out of the generated header.
    ///
    /// Parsed rather than kept alongside `state.json` so there is one copy of
    /// these on disk, in the file that is already gitignored for being secret.
    public func loadSecrets() throws -> Secrets {
        guard let text = try? String(contentsOf: secretsURL, encoding: .utf8) else {
            return Secrets()
        }
        var secrets = Secrets()
        for field in SecretField.allCases {
            if let value = Self.define(field.rawValue, in: text) {
                secrets[field] = value
            }
        }
        return secrets
    }

    /// The value of a `#define`, with the surrounding quotes dropped if present.
    static func define(_ name: String, in text: String) -> String? {
        let pattern = "^\\s*#define\\s+\(name)\\s+\"?([^\"\\n]*)\"?\\s*$"
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.anchorsMatchLines]),
              let match = regex.firstMatch(
                  in: text, range: NSRange(text.startIndex..., in: text)
              ),
              let range = Range(match.range(at: 1), in: text)
        else { return nil }
        return String(text[range]).trimmed
    }

    public func writeSecrets(_ secrets: Secrets) throws {
        let missing = [SecretField.wifiSSID, .mqttHost]
            .filter { secrets[$0].trimmed.isEmpty }
            .map(\.rawValue)
        if !missing.isEmpty {
            throw ConfigError("required and empty: \(missing.joined(separator: ", "))")
        }

        let port = secrets.mqttPort.trimmed.isEmpty ? "1883" : secrets.mqttPort.trimmed
        guard port.allSatisfy(\.isNumber) else {
            throw ConfigError("MQTT port must be a number, got '\(port)'")
        }

        let lines = [
            "#pragma once",
            "",
            Self.generatedBanner,
            "// This file is gitignored. Keep it that way -- it is the only place",
            "// these credentials are stored.",
            "",
            "#define WIFI_SSID \"\(escape(secrets.wifiSSID))\"",
            "#define WIFI_PASSWORD \"\(escape(secrets.wifiPassword))\"",
            "",
            "#define MQTT_HOST \"\(escape(secrets.mqttHost))\"",
            "#define MQTT_PORT \(port)",
            "#define MQTT_USERNAME \"\(escape(secrets.mqttUsername))\"",
            "#define MQTT_PASSWORD \"\(escape(secrets.mqttPassword))\"",
            "",
            "// Used by tools/ota_auth.py when uploading over the air.",
            "#define OTA_PASSWORD \"\(escape(secrets.otaPassword))\"",
            "",
        ]
        try createParentDirectory(of: secretsURL)
        try writeText(lines.joined(separator: "\n"), to: secretsURL)
    }

    // MARK: - validation

    /// Rejects anything that would build firmware that cannot work.
    ///
    /// Everything here fails silently on real hardware if it gets through: a
    /// duplicate location makes two remotes indistinguishable, an over-long one
    /// is truncated on the wire and then rejected by the hub, and a bad channel
    /// means the remote transmits where nothing is listening.
    public func validate(_ state: FlasherState) throws {
        guard !state.remotes.isEmpty else { throw ConfigError("add at least one remote") }

        var seen = Set<String>()
        for remote in state.remotes {
            let location = remote.location.trimmed
            guard Self.matches("^[a-z][a-z0-9_]*$", location) else {
                throw ConfigError(
                    "'\(location)' is not a usable location: lowercase letters, digits "
                    + "and underscores only, starting with a letter. It becomes part of "
                    + "an MQTT topic."
                )
            }
            guard location.count <= Self.maxLocationLength else {
                throw ConfigError(
                    "'\(location)' is \(location.count) characters; the packet holds "
                    + "\(Self.maxLocationLength)"
                )
            }
            guard !seen.contains(location) else {
                throw ConfigError("two remotes both called '\(location)'")
            }
            seen.insert(location)
            guard !remote.name.trimmed.isEmpty else {
                throw ConfigError("\(location): needs a display name")
            }
        }

        for reserved in Self.reservedLocations.sorted() where seen.contains(reserved) {
            throw ConfigError("'\(reserved)' is reserved -- a hub already uses it as its id")
        }

        guard (1...13).contains(state.wifiChannel) else {
            throw ConfigError("WiFi channel \(state.wifiChannel) is outside 1-13")
        }
        guard (100...5000).contains(state.holdThresholdMs) else {
            throw ConfigError("hold threshold \(state.holdThresholdMs)ms is outside 100-5000")
        }

        let topicRoot = state.topicRoot.trimmed
        guard !topicRoot.isEmpty, !topicRoot.contains("#"), !topicRoot.contains("+") else {
            throw ConfigError("topic root must be non-empty and free of + and #")
        }

        for hub in HubKind.allCases {
            let mac = state.mac(for: hub).trimmed
            guard mac.isEmpty || Self.isMac(mac) else {
                throw ConfigError("\(hub.rawValue) hub MAC '\(mac)' is not a MAC address")
            }
        }
    }

    public static func isMac(_ value: String) -> Bool {
        matches("^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$", value)
    }

    static func matches(_ pattern: String, _ value: String) -> Bool {
        value.range(of: pattern, options: .regularExpression) != nil
    }

    // MARK: - generated firmware config

    func deviceConfigText(_ state: FlasherState) -> String {
        var lines = [
            "#pragma once",
            "",
            Self.generatedBanner,
            "// Overrides the defaults in include/config.h, which picks this up",
            "// through __has_include. Gitignored: these values are yours, not the",
            "// repository's.",
            "",
            "#define WIFI_CHANNEL \(state.wifiChannel)",
            "#define HOLD_THRESHOLD_MS \(state.holdThresholdMs)",
            "#define TOPIC_ROOT \"\(escape(state.topicRoot.trimmed))\"",
            "",
        ]

        for hub in [HubKind.wired, .wireless] {
            let mac = state.mac(for: hub).trimmed
            guard !mac.isEmpty else { continue }
            let board = hub == .wired ? "WT32-ETH01" : "ESP32"
            lines.append(
                "#define \(hub.macMacro) \(Self.macToC(mac)) // \(board), \(mac.uppercased())"
            )
        }
        lines.append("")

        lines.append("#define REMOTE_LOCATION_TABLE(X) \\")
        let rows = state.remotes.map { "  X(\"\($0.location)\", \"\(escape($0.name))\")" }
        lines.append(rows.joined(separator: " \\\n"))
        lines.append("")

        return lines.joined(separator: "\n")
    }

    func localIniText(_ state: FlasherState) -> String {
        let environments = state.remotes.map(\.environment) + ["hub", "hub_eth"]
        var lines = [
            "; Generated by the ESP-NOW Remote Flasher app. Edits here are overwritten.",
            "; One environment per remote you configured. platformio.ini pulls this",
            "; in through `extra_configs = *_local.ini`, and same-named sections",
            "; here win, so this is the authority while it exists.",
            "",
            "[platformio]",
            "default_envs = \(environments.joined(separator: ", "))",
            "",
        ]
        for remote in state.remotes {
            lines += [
                "[env:\(remote.environment)]",
                "extends = remote_base",
                "build_flags = ${env.build_flags} "
                    + "-DREMOTE_LOCATION='\"\(remote.location)\"' "
                    + "-DHUB_MAC_ADDRESS=\(remote.hub.macMacro)",
                "",
            ]
        }
        return lines.joined(separator: "\n")
    }

    /// Validates, then writes both generated firmware files and the state.
    public func apply(_ state: FlasherState) throws {
        try validate(state)
        try createParentDirectory(of: deviceConfigURL)
        try writeText(deviceConfigText(state), to: deviceConfigURL)
        try writeText(localIniText(state), to: localIniURL)
        try saveState(state)
    }

    // MARK: - helpers

    static func macToC(_ mac: String) -> String {
        let bytes = mac.replacingOccurrences(of: "-", with: ":")
            .uppercased()
            .split(separator: ":")
            .map { "0x" + String(repeating: "0", count: max(0, 2 - $0.count)) + $0 }
        return "{ " + bytes.joined(separator: ", ") + " }"
    }

    func escape(_ value: String) -> String {
        value.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    private func createParentDirectory(of url: URL) throws {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true
        )
    }

    private func writeText(_ text: String, to url: URL) throws {
        try write(Data(text.utf8), to: url)
    }

    /// Writes atomically, translating the one failure that has a real cause
    /// worth naming.
    private func write(_ data: Data, to url: URL) throws {
        do {
            try data.write(to: url, options: .atomic)
        } catch let error as NSError where error.isPermissionDenied {
            throw ConfigError(
                "Cannot write \(url.lastPathComponent): permission denied.\n\n"
                + "macOS gates access to Desktop, Documents and Downloads per app. "
                + "Grant it under System Settings > Privacy & Security > Files and "
                + "Folders, or keep the project somewhere outside those folders."
            )
        }
    }
}

extension NSError {
    var isPermissionDenied: Bool {
        (domain == NSPOSIXErrorDomain && code == Int(EACCES))
            || (domain == NSCocoaErrorDomain && code == NSFileWriteNoPermissionError)
    }
}
