"""Reads and writes everything the flasher generates.

Three files come out of here, all gitignored:

  include/secrets.h          credentials, the same file you would hand-copy
                             from secrets.example.h
  include/device_config.h    hub MACs, rooms, channel -- overrides the
                             defaults in include/config.h
  platformio_local.ini       one build environment per configured remote

state.json holds everything except the credentials. Those are read back out of
secrets.h instead of being duplicated, so there is exactly one copy of your
passwords on disk rather than two.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
STATE = Path(__file__).resolve().parent / "state.json"
SECRETS = ROOT / "include" / "secrets.h"
DEVICE_CONFIG = ROOT / "include" / "device_config.h"
LOCAL_INI = ROOT / "platformio_local.ini"

GENERATED_BANNER = "// Generated by tools/flasher. Edits here are overwritten.\n"

# name -> (default, is_secret). Secrets live in secrets.h; the rest in state.json.
SECRET_FIELDS = {
    "WIFI_SSID": "",
    "WIFI_PASSWORD": "",
    "MQTT_HOST": "",
    "MQTT_PORT": "1883",
    "MQTT_USERNAME": "",
    "MQTT_PASSWORD": "",
    "OTA_PASSWORD": "",
}

DEFAULT_STATE = {
    "wifi_channel": 1,
    "topic_root": "home",
    "hold_threshold_ms": 500,
    "hub_mac_wired": "",
    "hub_mac_wireless": "",
    "remotes": [
        {"location": "livingroom", "name": "Living Room Remote", "hub": "wired"},
    ],
}

MAC_RE = re.compile(r"^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$")
LOCATION_RE = re.compile(r"^[a-z][a-z0-9_]*$")

# Mirrors MAX_LOCATION_LEN in include/config.h. A longer name is silently
# truncated on the wire, and the hub then rejects the packet, so it is caught
# here where the message can say why.
MAX_LOCATION_LEN = 15


class ConfigError(ValueError):
    """Raised for input that would generate firmware that cannot work."""


# --------------------------------------------------------------------------
# state.json
# --------------------------------------------------------------------------


def load_state():
    state = dict(DEFAULT_STATE)
    if STATE.exists():
        try:
            state.update(json.loads(STATE.read_text()))
        except json.JSONDecodeError:
            pass  # Corrupt state should not lock you out of the UI.
    return state


def save_state(state):
    STATE.write_text(json.dumps(state, indent=2) + "\n")


# --------------------------------------------------------------------------
# secrets.h -- read back rather than duplicated into state.json
# --------------------------------------------------------------------------


def load_secrets():
    values = dict(SECRET_FIELDS)
    if not SECRETS.exists():
        return values
    text = SECRETS.read_text()
    for name in SECRET_FIELDS:
        m = re.search(rf'^\s*#define\s+{name}\s+"?([^"\n]*)"?\s*$', text, re.M)
        if m:
            values[name] = m.group(1).strip()
    return values


def write_secrets(values):
    missing = [k for k in ("WIFI_SSID", "MQTT_HOST") if not values.get(k, "").strip()]
    if missing:
        raise ConfigError(f"required and empty: {', '.join(missing)}")

    port = str(values.get("MQTT_PORT", "1883")).strip() or "1883"
    if not port.isdigit():
        raise ConfigError(f"MQTT port must be a number, got {port!r}")

    lines = [
        "#pragma once",
        "",
        GENERATED_BANNER.rstrip("\n"),
        "// This file is gitignored. Keep it that way -- it is the only place",
        "// these credentials are stored.",
        "",
        f'#define WIFI_SSID "{_escape(values["WIFI_SSID"])}"',
        f'#define WIFI_PASSWORD "{_escape(values["WIFI_PASSWORD"])}"',
        "",
        f'#define MQTT_HOST "{_escape(values["MQTT_HOST"])}"',
        f"#define MQTT_PORT {port}",
        f'#define MQTT_USERNAME "{_escape(values["MQTT_USERNAME"])}"',
        f'#define MQTT_PASSWORD "{_escape(values["MQTT_PASSWORD"])}"',
        "",
        "// Used by tools/ota_auth.py when uploading over the air.",
        f'#define OTA_PASSWORD "{_escape(values["OTA_PASSWORD"])}"',
        "",
    ]
    SECRETS.write_text("\n".join(lines))


def _escape(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


# --------------------------------------------------------------------------
# generated firmware config
# --------------------------------------------------------------------------


def validate_state(state):
    """Rejects anything that would build firmware that cannot work.

    Everything here fails silently on real hardware if it gets through: a
    duplicate location makes two remotes indistinguishable, an over-long one is
    truncated on the wire and then rejected by the hub, and a bad channel means
    the remote transmits where nothing is listening.
    """
    remotes = state.get("remotes", [])
    if not remotes:
        raise ConfigError("add at least one remote")

    seen = set()
    for remote in remotes:
        location = (remote.get("location") or "").strip()
        name = (remote.get("name") or "").strip()
        if not LOCATION_RE.match(location):
            raise ConfigError(
                f"{location!r} is not a usable location: lowercase letters, "
                "digits and underscores only, starting with a letter. It "
                "becomes part of an MQTT topic."
            )
        if len(location) > MAX_LOCATION_LEN:
            raise ConfigError(
                f"{location!r} is {len(location)} characters; the packet holds "
                f"{MAX_LOCATION_LEN}"
            )
        if location in seen:
            raise ConfigError(f"two remotes both called {location!r}")
        seen.add(location)
        if not name:
            raise ConfigError(f"{location}: needs a display name")
        if remote.get("hub") not in ("wired", "wireless"):
            raise ConfigError(f"{location}: pick which hub it talks to")

    # A location colliding with a hub id would collide on the node id too.
    for reserved in ("wifi", "eth"):
        if reserved in seen:
            raise ConfigError(
                f"{reserved!r} is reserved -- a hub already uses it as its id"
            )

    channel = int(state.get("wifi_channel", 1))
    if not 1 <= channel <= 13:
        raise ConfigError(f"WiFi channel {channel} is outside 1-13")

    hold = int(state.get("hold_threshold_ms", 500))
    if not 100 <= hold <= 5000:
        raise ConfigError(f"hold threshold {hold}ms is outside 100-5000")

    topic_root = (state.get("topic_root") or "").strip()
    if not topic_root or "#" in topic_root or "+" in topic_root:
        raise ConfigError("topic root must be non-empty and free of + and #")

    for key, label in (("hub_mac_wired", "wired"), ("hub_mac_wireless", "wireless")):
        mac = (state.get(key) or "").strip()
        if mac and not MAC_RE.match(mac):
            raise ConfigError(f"{label} hub MAC {mac!r} is not a MAC address")

    # Deliberately not checked here: whether the hub a remote points at has a
    # known MAC. You define remotes before flashing a hub, so demanding it at
    # save time would block the normal order of work. It is enforced at the
    # point it actually matters -- see missing_hub_mac().
    return True


def missing_hub_mac(state, location):
    """Which hub a remote needs the address of, or None if it is ready.

    A remote built against the placeholder MAC transmits into nothing, and
    ESP-NOW reports no error it could act on, so this is the one place to stop
    it: refuse the flash rather than hand over firmware that fails silently.
    """
    for remote in state.get("remotes", []):
        if remote.get("location") == location:
            hub = remote.get("hub")
            if not (state.get(f"hub_mac_{hub}") or "").strip():
                return hub
            return None
    return None


def _mac_to_c(mac):
    return "{ " + ", ".join(f"0x{b:0>2}" for b in mac.replace("-", ":").upper().split(":")) + " }"


def write_device_config(state):
    lines = [
        "#pragma once",
        "",
        GENERATED_BANNER.rstrip("\n"),
        "// Overrides the defaults in include/config.h, which picks this up",
        "// through __has_include. Gitignored: these values are yours, not the",
        "// repository's.",
        "",
        f"#define WIFI_CHANNEL {int(state['wifi_channel'])}",
        f"#define HOLD_THRESHOLD_MS {int(state['hold_threshold_ms'])}",
        f'#define TOPIC_ROOT "{_escape(state["topic_root"].strip())}"',
        "",
    ]

    for key, macro, label in (
        ("hub_mac_wired", "HUB_MAC_WIRED", "WT32-ETH01"),
        ("hub_mac_wireless", "HUB_MAC_WIRELESS", "ESP32"),
    ):
        mac = (state.get(key) or "").strip()
        if mac:
            lines.append(f"#define {macro} {_mac_to_c(mac)} // {label}, {mac.upper()}")
    lines.append("")

    lines.append("#define REMOTE_LOCATION_TABLE(X) \\")
    rows = [
        f'  X("{r["location"]}", "{_escape(r["name"])}")'
        for r in state["remotes"]
    ]
    lines.append(" \\\n".join(rows))
    lines.append("")

    DEVICE_CONFIG.write_text("\n".join(lines))


def write_local_ini(state):
    envs = [f"remote_{r['location']}" for r in state["remotes"]]
    lines = [
        "; Generated by tools/flasher. Edits here are overwritten.",
        "; One environment per remote you configured. platformio.ini pulls this",
        "; in through `extra_configs = *_local.ini`, and same-named sections",
        "; here win, so this is the authority while it exists.",
        "",
        "[platformio]",
        f"default_envs = {', '.join(envs + ['hub', 'hub_eth'])}",
        "",
    ]
    for remote in state["remotes"]:
        macro = "HUB_MAC_WIRED" if remote["hub"] == "wired" else "HUB_MAC_WIRELESS"
        lines += [
            f"[env:remote_{remote['location']}]",
            "extends = remote_base",
            f"build_flags = ${{env.build_flags}} "
            f"-DREMOTE_LOCATION='\"{remote['location']}\"' "
            f"-DHUB_MAC_ADDRESS={macro}",
            "",
        ]
    LOCAL_INI.write_text("\n".join(lines))


def apply(state):
    """Validates, then writes both generated firmware files."""
    validate_state(state)
    write_device_config(state)
    write_local_ini(state)
    save_state(state)
